"""Applying nullable=True for CPF

Revision ID: 0ebb27680b61
Revises: f0d76e45da59
Create Date: 2025-03-31 22:07:29.778768

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ebb27680b61"  # pragma: allowlist secret
down_revision = "f0d76e45da59"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.alter_column("cpf", existing_type=sa.VARCHAR(length=14), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.alter_column("cpf", existing_type=sa.VARCHAR(length=14), nullable=False)

    # ### end Alembic commands ###
