"""add temp_diet_file to diets

Revision ID: 396dcef009c7
Revises: 6eeb36dbe48d
Create Date: 2025-04-13 16:11:29.670025

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "396dcef009c7"  # pragma: allowlist secret
down_revision = "6eeb36dbe48d"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("temp_diet_file", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diets", schema=None) as batch_op:
        batch_op.drop_column("temp_diet_file")

    # ### end Alembic commands ###
