"""Move campo peso para skinfolds

Revision ID: 52b58f265b63
Revises:
Create Date: 2025-03-27 22:18:49.212255

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52b58f265b63"  # pragma: allowlist secret
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.drop_column("peso")

    with op.batch_alter_table("skinfolds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("peso", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skinfolds", schema=None) as batch_op:
        batch_op.drop_column("peso")

    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("peso", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
