"""removing unique key from cpf and email

Revision ID: 63fef06f250f
Revises: 207009c1bb68
Create Date: 2025-04-03 11:18:53.147613

"""
import sqlalchemy as sa  # noqa
from alembic import op

# revision identifiers, used by Alembic.
revision = "63fef06f250f"  # pragma: allowlist secret
down_revision = "207009c1bb68"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_constraint("patients_cpf_key", type_="unique")
        batch_op.drop_constraint("patients_email_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_unique_constraint("patients_email_key", ["email"])
        batch_op.create_unique_constraint("patients_cpf_key", ["cpf"])

    # ### end Alembic commands ###
