"""Renomeia coluna pdf_file para diet_file em Diet

Revision ID: 6eeb36dbe48d
Revises: 63fef06f250f
Create Date: 2025-04-09 12:05:29.515347

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6eeb36dbe48d"  # pragma: allowlist secret
down_revision = "63fef06f250f"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("diet_file", sa.String(length=255), nullable=True))
        batch_op.drop_column("pdf_file")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pdf_file", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column("diet_file")

    # ### end Alembic commands ###
