"""Migrate altura to skinfolds table

Revision ID: b260e31a1352
Revises: f1151a160268
Create Date: 2025-03-29 14:10:29.273137

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b260e31a1352"  # pragma: allowlist secret
down_revision = "f1151a160268"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.drop_column("altura")

    with op.batch_alter_table("skinfolds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("altura", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skinfolds", schema=None) as batch_op:
        batch_op.drop_column("altura")

    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("altura", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
