"""increase length of ultima_guia characters

Revision ID: e597d0bd19ee
Revises: 396dcef009c7
Create Date: 2025-06-30 15:29:28.177843

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e597d0bd19ee"  # pragma: allowlist secret
down_revision = "396dcef009c7"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.alter_column(
            "ultima_guia", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=255), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.alter_column(
            "ultima_guia", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=20), existing_nullable=False
        )

    # ### end Alembic commands ###
