"""Migrate idade_metabolica to skinfolds table

Revision ID: f1151a160268
Revises: 52b58f265b63
Create Date: 2025-03-29 13:43:12.835546

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1151a160268"  # pragma: allowlist secret
down_revision = "52b58f265b63"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.drop_column("idade_metabolica")

    with op.batch_alter_table("skinfolds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("idade_metabolica", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skinfolds", schema=None) as batch_op:
        batch_op.drop_column("idade_metabolica")

    with op.batch_alter_table("anthropometric_evaluations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("idade_metabolica", sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
