"""add order column to diets

Revision ID: fb739ba57804
Revises: e597d0bd19ee
Create Date: 2025-10-08 19:51:34.530208

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb739ba57804"  # pragma: allowlist secret
down_revision = "e597d0bd19ee"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("diets", schema=None) as batch_op:
        batch_op.drop_column("order")

    # ### end Alembic commands ###
